"""Deterministic ID generation — single source of truth for all UUID namespaces.

Every entity's namespace UUID is defined here. Using a consistent namespace
ensures that IDs generated during ingestion match IDs generated by the API
for the same logical entity, making operations idempotent across runs.

Key format must never change after data has been written — changing the format
would orphan every existing node.
"""
import uuid

# Single namespace for works and authors (prefix distinguishes them in the key)
_WORKS_AUTHOR_NS = uuid.UUID("12345678-1234-5678-1234-567812345678")

# Namespace for collections — keyed on normalised name
_COLLECTION_NS = uuid.UUID("c3f5a9e0-1111-4444-8888-000000000002")

# Namespace for streams — keyed on normalised name
_STREAM_NS = uuid.UUID("c3f5a9e0-1111-4444-8888-000000000003")

# Namespace for series — keyed on normalised name
_SERIES_NS = uuid.UUID("c3f5a9e0-1111-4444-8888-000000000004")


def work_id(title: str, author_name: str) -> str:
    """Matches the key scheme used in ingestion/reading_list.py."""
    return str(uuid.uuid5(_WORKS_AUTHOR_NS, f"work:{author_name}|{title}"))


def author_id(name: str) -> str:
    """Matches the key scheme used in ingestion/reading_list.py."""
    return str(uuid.uuid5(_WORKS_AUTHOR_NS, f"author:{name}"))


def collection_id(name: str) -> str:
    return str(uuid.uuid5(_COLLECTION_NS, name.strip().lower()))


def stream_id(name: str) -> str:
    return str(uuid.uuid5(_STREAM_NS, name.strip().lower()))


def series_id(name: str) -> str:
    return str(uuid.uuid5(_SERIES_NS, name.strip().lower()))
